"""users table

Revision ID: 16dc27cb6844
Revises: 5f62d472470d
Create Date: 2020-07-14 12:21:24.571476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16dc27cb6844'
down_revision = '5f62d472470d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('transaction_type', sa.String(), nullable=True))
    op.drop_column('orders', 'type')
    op.drop_column('orders', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'transaction_type')
    op.drop_column('orders', 'company_name')
    # ### end Alembic commands ###
