"""orders table

Revision ID: 9ad6936b583a
Revises: ed27e4be7ad9
Create Date: 2020-07-14 18:06:16.121407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ad6936b583a'
down_revision = 'ed27e4be7ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', sa.DateTime(), nullable=True))
    op.drop_column('orders', 'transaction_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###
